### ISSUE TITLE
Modification on final report

### ISSUE THREAD

**Issue by thomassiu** [UBC-MDS/Crime_Prediction_Vancouver#69]
Hi Jasmine,

Can you remove library(tidyverse) in the final report (vancouver_crime_predict_report.Rmd) as it is not being used. This is to align the absence of tidyverse package installed for M1 users.

Thanks
Thomas

**Comment by jasmineortega** [comment]
I just created the PR

**Comment by thomassiu** [comment]
This is completed as per #73
